name: Main

on:
  push:
    branches:
    - main

jobs:
  small-step:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # Needed to request a new token with aud=smallstep

    name: Install Cosign and test presence in path
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Install step-cli
      run: |
        wget https://dl.step.sm/gh-release/cli/docs-cli-install/v0.21.0/step-cli_0.21.0_amd64.deb
        sudo dpkg -i step-cli_0.21.0_amd64.deb

    - name: Get a github token for Smallstep CA
      run: |
        set -x
        echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
        echo $ACTIONS_ID_TOKEN_REQUEST_URL
        curl -v -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=smallstep" > token
        cat token
        cat token | step crypto jwt inspect --insecure

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
